### ISSUE TITLE
AHKBendableView reacting to scroll view velocity

### ISSUE THREAD

**Issue by SimplGy** [fastred/AHKBendableView#6]
I'd like to make a scroll view that contains a single AHKBendableView which responds to vertical scroll velocity.

It looks like BendableView updates itself based on current/previous position inside animation blocks, but it's not clear to me how this would work in a scroll view. Sorry I'm pretty new at this stuff.

I could map velocity -> control points like [BRFlabbyTable does](https://github.com/brocoo/BRFlabbyTable/blob/d821cca0cde50d95b4140ca9e3259b12209b732f/Classes/BRFlabbyTableViewCell.m#L53). But maybe the animation feels more realistic using springs as you do, and maybe it's less code to write. You think this is a good use case for AHKBendableView, maybe by plugging vertical velocity into it, or by manually tracking it's position to match the scrollview?

**Comment by fastred** [comment]
Hi! I think that `AHKBendableView`'s API doesn't match your use case.

Here's how I'd approach this problem:
1. In `- scrollViewDidScroll:` I'd check how much time went since it was last called and how much the vertical offset changed.
2. I'd use these two values to calculate the velocity.
3. Based on the velocity I'd choose the control points of `UIBezierPath` to look like the background of the cell is bending.

I didn't check `BRFlabbyTable` source. Maybe that's how they do it.

**Comment by SimplGy** [comment]
Thanks for the reply, that's super thoughtful of you.

I ended up with almost exactly what you suggest. There's some corner case detection in reading the velocity from scroll view, like if you scroll to the top and it stops abruptly, but these are easily managed.

The end result is surprisingly convincing, given it lacks any kind of real physics.

      private func drawCurvedPath(curveAmount: CGFloat) -> CGPath {
        
        // TODO: I can refactor a lot of the dimensions calculations into didLayoutSubviews or similar
        let height = bounds.height //:CGFloat = 100
        let width  = bounds.width
        let top    = bounds.origin.y - borderWidth / 2
        let left   = bounds.origin.x - borderWidth / 2
        let right  = bounds.origin.x + width  + borderWidth
        let bottom = bounds.origin.y + height + borderWidth + extraRoomBelow
        let path = UIBezierPath()
        var wiggle = top - curveAmount * multiplier
        
        path.moveToPoint(CGPoint(x: left, y: wiggle))
        
        // Next up: curvable line to center top, and another curvable line to top right
        path.addCurveToPoint(CGPoint(x: left + width/2, y: top),
          controlPoint1: CGPoint(x: left, y: wiggle), // putting it on top of the start point makes it unused
          controlPoint2: CGPoint(x: left + (width/4), y: top)
        )
        path.addCurveToPoint(CGPoint(x: right, y: wiggle),
          controlPoint1: CGPoint(x: right - (width/4), y: top),
          controlPoint2: CGPoint(x: right, y: wiggle) // putting it on top of the destination makes it unused
        )
        
        path.addLineToPoint(CGPoint(x: right, y: bottom))
        path.addLineToPoint(CGPoint(x: left, y: bottom))
        path.closePath()
        
        return path.CGPath
      }

**Comment by fastred** [comment]
I'm glad to hear that my advice helped you.
